image:
  repository: b4bz/homer
  tag: latest
  pullPolicy: IfNotPresent


service:
  main:
    enabled: true
    ports:
      http:
        port: 8080

ingress:
  main:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
    hosts:
    - host: user.example.com
      paths:
      - path: /
        pathType: Prefix

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi

autoscaling:
  enabled: true
  target:  # deploymentname
  minReplicas:  # 1
  maxReplicas:  # 100
  targetCPUUtilizationPercentage:  # 80
  targetMemoryUtilizationPercentage:  # 80
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 30
      policies:
      - type: Percent
        value: 100
        periodSeconds: 15
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
  externalMetrics:
  - name: queue_length
    target:
      type: Value
      value: "5"
    selector:
      component: test-queue

