apiVersion: v2
name: common
description: Function library for blissflow charts
type: library
version: 4.8.1
kubeVersion: ">=1.16.0-0"
keywords:
  - blissflow
  - common
home: https://github.com/blissflow/library-charts/tree/main/stable/common
maintainers:
  - name: bjw-s
    email: me@bjw-s.dev
  - name: onedr0p
    email: devin.kray@gmail.com
  - name: dirtycajunrice
    email: nick@cajun.pro
