name: "Charts: Lint and test"

on:
  pull_request:
    paths:
    - '.github/workflows/charts-lint-test.yaml'
    - 'charts/**'
    - 'helper-charts/**'

jobs:
  lint:
    name: Lint charts
    runs-on: ubuntu-latest
    outputs:
      changed: ${{ steps.list-changed.outputs.changed }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install Helm
      uses: azure/setup-helm@v4
      with:
        version: v3.17.3

    - uses: actions/setup-python@v5
      with:
        python-version: 3.8

    - name: Set up chart-testing
      uses: helm/chart-testing-action@v2.7.0

    - name: Run chart-testing (list-changed)
      id: list-changed
      run: |
        changed=$(ct list-changed --config .github/ct-lint.yaml)
        if [[ -n "$changed" ]]; then
          echo "::set-output name=changed::true"
        fi

    - name: Run chart-testing (lint)
      id: lint
      if: steps.list-changed.outputs.changed == 'true'
      run: ct lint --config .github/ct-lint.yaml

  unittest:
    needs:
    - lint
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install Helm
      uses: azure/setup-helm@v4
      with:
        version: v3.17.3

    - name: Run tests
      run: |
        helm plugin install https://github.com/helm-unittest/helm-unittest.git --version v0.8.2
        cd helper-charts/common-test/
        helm unittest -f "tests/**/*_test.yaml" .

  install:
    needs:
    - lint
    name: Install charts
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install Helm
      uses: azure/setup-helm@v4
      with:
        version: v3.17.3

    - uses: actions/setup-python@v5
      with:
        python-version: 3.8

    - name: Set up chart-testing
      uses: helm/chart-testing-action@v2.7.0

    - name: Create k3d cluster
      uses: nolar/setup-k3d-k3s@v1
      with:
        version: v1.19
      if: needs.lint.outputs.changed == 'true'

    - name: Run chart-testing (install)
      run: ct install --config .github/ct-install.yaml
      if: needs.lint.outputs.changed == 'true'
