name: Label PRs based on CI status
on:
  workflow_run:
    workflows:
      - 'Pre-commit consistency check'
      - 'Install and Lint'
    types:
      - completed

permissions:
  contents: read
  pull-requests: write
  actions: read

jobs:
  label-precommit:
    name: Label pre-commit status
    runs-on: ubuntu-20.04
    if: "${{ github.event.workflow.name == 'Pre-commit consistency check' }}"
    steps:
      - name: "Get information about the origin 'CI' run"
        uses: potiuk/get-workflow-origin@v1_3
        id: source-run-info
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          sourceRunId: ${{ github.event.workflow_run.id }}

      - name: Label precommit success
        uses: andymckay/labeler@1.0.4
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ steps.source-run-info.outputs.pullRequestNumber }}
          add-labels: "precommit:ok"
          remove-labels: "precommit:failed"

      - name: Label precommit failure
        uses: andymckay/labeler@1.0.4
        if: ${{ github.event.workflow_run.conclusion == 'failure' }}
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ steps.source-run-info.outputs.pullRequestNumber }}
          add-labels: "precommit:failed"
          remove-labels: "precommit:ok"

  label-lint-install:
    name: Label lint and install status
    runs-on: ubuntu-20.04
    if: "${{ github.event.workflow.name == 'Install and Lint' }}"
    steps:
      - name: "Get information about the origin 'CI' run"
        uses: potiuk/get-workflow-origin@v1_3
        id: source-run-info
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          sourceRunId: ${{ github.event.workflow_run.id }}

      - name: Label lint success
        uses: andymckay/labeler@1.0.4
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ steps.source-run-info.outputs.pullRequestNumber }}
          add-labels: "lint:ok"
          remove-labels: "lint:failed"

      - name: Label lint failure
        uses: andymckay/labeler@1.0.4
        if: ${{ github.event.workflow_run.conclusion == 'failure' }}
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ steps.source-run-info.outputs.pullRequestNumber }}
          add-labels: "lint:failed"
          remove-labels: "lint:ok"

