name: "Metadata: Validate PR title format"

on:
  pull_request_target:
    types:
      - opened
      - edited
      - reopened
      - ready_for_review
      - synchronize

jobs:
  label-title:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read
    steps:
      - name: Validate PR title and label if incorrect
        uses: actions/github-script@v7
        with:
          script: |
            const title = context.payload.pull_request.title;
            const prNumber = context.payload.pull_request.number;
            const creator = context.payload.pull_request.user.login;

            const isBot = creator.toLowerCase().includes('renovate');
            const matchesFormat = /^\[[a-z0-9\-]+\]\s[A-Z0-9].+/.test(title);

            if (!isBot && !matchesFormat) {
              const label = 'kind:incorrect-title';

              const existingLabels = context.payload.pull_request.labels.map(l => l.name);
              if (!existingLabels.includes(label)) {
                await github.rest.issues.addLabels({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: prNumber,
                  labels: [label],
                });
              }
            }

